version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:      
      - discovery.type=single-node    
      - xpack.security.enrollment.enabled=false
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432

  web:
    build: .
    working_dir: /
    depends_on:
        - elasticsearch
    volumes:
      - './app:/app'   
    ports:
      - '8990:8989'

  